In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

c:\Program Files\Python313\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [5]:
model = Sequential()

model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))

c:\Program Files\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[ 0.1963731 , -0.93548197],
        [ 0.41122282,  0.95356   ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6197839],
        [ 1.3812808]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [
	np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),  # dense1 kernel (2,2)
	np.array([0., 0.], dtype=np.float32),                 # dense1 bias (2,)
	np.array([[0.1], [0.1]], dtype=np.float32),            # dense2 kernel (2,1)
	np.array([0.0], dtype=np.float32)                      # dense2 bias (1,)
]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: 26.6692
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 22.7181 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 18.7587
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 13.3731
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 8.7572
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.1680
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9658    
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9700 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1211 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.5031
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.6979
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.4989
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1738
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0840
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1113
Epoch 16/75
4/4 ━━━━━━━━━

In [13]:
model.get_weights()

[array([[0.04048812, 0.04048812],
        [0.5687266 , 0.5687266 ]], dtype=float32),
 array([0.23208314, 0.23208314], dtype=float32),
 array([[0.43815792],
        [0.43815792]], dtype=float32),
 array([0.24060428], dtype=float32)]