In [1]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

c:\Program Files\Python313\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
model = Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

c:\Program Files\Python313\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
print(model.get_weights()[0].shape)  # weights of the RNN layer
model.get_weights()[0]  # weights of the RNN layer

(5, 3)


array([[ 0.04330742,  0.8124817 , -0.03598702],
       [-0.5181531 ,  0.08931822, -0.17773294],
       [-0.11358297,  0.7158845 , -0.546696  ],
       [-0.34534132, -0.6439072 , -0.13027471],
       [-0.18778074,  0.6478453 ,  0.31106263]], dtype=float32)

In [5]:
print(model.get_weights()[1].shape)  # weights of the RNN layer
model.get_weights()[1]  # weights of the RNN layer

(3, 3)


array([[ 0.8989432 , -0.36010465,  0.24945116],
       [ 0.16416529, -0.2510142 , -0.95396096],
       [ 0.4061416 ,  0.89850783, -0.16653092]], dtype=float32)

In [6]:
print(model.get_weights()[2].shape)  # weights of the RNN layer
model.get_weights()[2]  # weights of the RNN layer

(3,)


array([0., 0., 0.], dtype=float32)